"""Generate the fixed-geometry #83 table; quadrature is not a proof."""

from pathlib import Path

from null_mixed import SineMixedCap, action_error_bound


def report():
    cap = SineMixedCap(T=1.0, epsilon=0.2)
    area = cap.joint_area(96)
    rows = [
        "# Fixed-null mixed-cap diagnostics (#83)",
        "",
        "Generated by `.venv/bin/python reproduce_null_mixed.py` using the pinned",
        "Python dependencies. IEEE float64 quadrature, not certified numerical errors,",
        "a Lean proof, or a Poisson expectation computation. See the",
        "[written estimates and claim boundary](../notes/null-mixed-estimates.md).",
        "",
        "Geometry is fixed: `H(x) = 1 + 0.2 sin(x_1)`.",
        f"Independent screen-area quadrature (angular order 96): **{area:.10f}**.",
        f"Independent ordinary-coordinate volume: **{cap.volume(96):.10f}**.",
        "",
        "## Reduced full-partner action",
        "",
        "The last column evaluates (NM7) at the same fixed squared-proper-time split",
        "`s=0.01` in every row; it is deliberately conservative. Its written proof is",
        "separate from the quadrature accuracy. Geometry does not vary with density.",
        "",
        "| Density | Order 32 | Order 64 | Refinement difference (not a bound) | Distance from area | Analytic bound |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    for rho in (10, 100, 1000, 10000, 1000000):
        low, high = (cap.action(rho, order) for order in (32, 64))
        bound = action_error_bound(rho, 0.01, cap.T, cap.epsilon)
        rows.append(f"| {rho} | {low:.10f} | {high:.10f} | {abs(high-low):.3g} "
                    f"| {abs(high-area):.6g} | {bound:.6g} |")
    rows += [
        "",
        "The scaled Gaussian quadrature cuts off at `u=10` when needed; its analytic",
        "omitted tail is at most `area * erfc(10)`. Root, angular and outer quadrature",
        "errors remain separate and uncertified. Agreement under refinement is not",
        "a substitute for the independent coordinate tests in `test_null_mixed.py`.",
        "",
        "## Radial-slice negative control",
        "",
        "At `sigma=1.01`, `mu=1`, the radial slice has two positive endpoints:",
    ]
    lower, upper = cap.radial_slice(1.01, 1)
    rows += [
        f"`({lower:.10f}, {upper:.10f})`. Angular quadrature estimates for the",
        "full weight at this slice (a nonsmooth angular support edge) are:",
        "",
        "| Angular order | Weight estimate (not certified) |",
        "| --- | --- |",
        *[f"| {order} | {cap.weight(1.01, order):.10f} |" for order in (32, 64, 96)],
        "",
        "The slice weight is less well resolved than the integrated action; its",
        "displayed digits are not an accuracy claim. Assuming all slices start",
        "at radius zero, or vanish above `H(0)^2`,",
        "would change the actual finite-density action.",
        "",
        "## Scope",
        "",
        "The unit joint coefficient comes with a generator-derivative term for",
        "general source weights. Tip and collar complements cannot be dropped at",
        "fixed cutoff. These computations support the written all-partner estimates;",
        "#84 still owns the integrated region/area/Poisson assembly. No additional",
        "null strata, geometry-limit interchange, or individual-sprinkling result",
        "is inferred.",
        "",
    ]
    return "\n".join(rows)


if __name__ == "__main__":
    path = Path(__file__).resolve().parent / "results" / "null-mixed.md"
    path.write_text(report())
    print(path)
