"""Print deterministic Markdown tables; these are not Monte Carlo estimates."""

from mpmath import mp

from calculations import ellipsoid_action, ellipsoid_limit, null_cap_action, null_cap_area


def main():
    mp.dps = 40
    print("# Numerical consistency checks\n")
    print("Generated by `.venv/bin/python reproduce.py` at 40 decimal digits.")
    print("Displayed values are rounded. These checks support, but do not prove,")
    print("the limit arguments in `notes/first-attempt.md`.\n")
    print("All actions below mean `l_p² E[S⁽⁴⁾_ρ]/ℏ` in fixed length units.\n")

    print("## Null-plane-truncated diamond\n")
    print("`T=1`, `a=1/2`; predicted limit `3π/4` = " + mp.nstr(null_cap_area(1, "0.5"), 18) + ".\n")
    print("| Density ρ | Finite-density action | Action / predicted limit |")
    print("|---:|---:|---:|")
    limit = null_cap_area(1, "0.5")
    for exponent in (4, 6, 8, 10, 12):
        action = null_cap_action(10**exponent, 1, "0.5")
        print(f"| 10^{exponent} | {mp.nstr(action, 16)} | {mp.nstr(action / limit, 16)} |")

    print("\n## Ellipsoidal cap with variable joint angle\n")
    print("`(b₁,b₂,b₃)=(1,2,3)`, `a=1/4`.")
    print("The angle is not constant: `tanh θ` ranges from `1/6` to `1/2`.")
    print("Predicted limit `48π` = " + mp.nstr(ellipsoid_limit("0.25", (1, 2, 3)), 18) + ".\n")
    print("| Density ρ | Finite-density action | Action / predicted limit |")
    print("|---:|---:|---:|")
    limit = ellipsoid_limit("0.25", (1, 2, 3))
    for exponent in (4, 6, 8, 10, 12):
        action = ellipsoid_action(10**exponent, "0.25", (1, 2, 3))
        print(f"| 10^{exponent} | {mp.nstr(action, 16)} | {mp.nstr(action / limit, 16)} |")

    print("\nThe two examples approach from opposite sides. The graph-cap kernel")
    print("is signed; keeping only its positive part would give the wrong limit.")


if __name__ == "__main__":
    main()
