apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
images:
- name: ghcr.io/q5m-ai/causal-set-emergence
  newName: ghcr.io/q5m-ai/causal-set-emergence
  digest: sha256:b31f913ab33fbe01c527540e33583a837e5ef8d3f563cfeaacb3983b403ef1bf
patches:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: web
  patch: |-
    - op: add
      path: /spec/template/metadata/annotations
      value:
        q5m.ai/release: 8935c158d137adad04a48fa872f8caff09da18e9
