apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
images:
- name: ghcr.io/q5m-ai/causal-set-emergence
  newName: ghcr.io/q5m-ai/causal-set-emergence
  digest: sha256:e93e516c3b44d735931f6f621d1078a3832053a52dd2bb8ceb3f14e106585d79
patches:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: web
  patch: |-
    - op: add
      path: /spec/template/metadata/annotations
      value:
        q5m.ai/release: 4d77e959dc7d75cb383ad862b7d645b0735c998b
