apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
images:
- name: ghcr.io/q5m-ai/causal-set-emergence
  newName: ghcr.io/q5m-ai/causal-set-emergence
  digest: sha256:17c550da4f0f7ce299fbe807e4c5e571b4c05433530f03847ed2fbd0a31bfced
patches:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: web
  patch: |-
    - op: add
      path: /spec/template/metadata/annotations
      value:
        q5m.ai/release: 12a07223b26679f76f55ef8d86683e5e647b0e25
