pid /tmp/nginx.pid;
error_log /dev/stderr warn;

worker_processes auto;
events {
    worker_connections 256;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    access_log /dev/stdout;
    sendfile on;
    server_tokens off;

    client_body_temp_path /tmp/client-body;
    proxy_temp_path /tmp/proxy;
    fastcgi_temp_path /tmp/fastcgi;
    uwsgi_temp_path /tmp/uwsgi;
    scgi_temp_path /tmp/scgi;

    server {
        listen 8080;
        root /usr/share/nginx/html;
        index index.html;

        add_header X-Content-Type-Options nosniff always;
        add_header Referrer-Policy strict-origin-when-cross-origin always;

        location ~ ^/(startupz|readyz|livez|healthz)$ {
            access_log off;
            default_type text/plain;
            return 200 "healthy\n";
        }

        location = /.q5m-release {
            access_log off;
            default_type text/plain;
            try_files $uri =404;
        }

        location / {
            try_files $uri $uri/ =404;
        }
    }
}
